experiment_name: pls_nc15_emsc
group_col: species number
id_col: sample number
model_params:
  n_components: 15
model_type: pls
n_folds: 5
preprocess:
- name: emsc
- deriv: 1
  name: sg
  polyorder: 2
  window_length: 7
- name: standard_scaler
seed: 42
shuffle: true
split_method: group_kfold
target_col: 含水率
test_file: test.csv
train_file: train.csv
