experiment_name: sklearn_gb
group_col: species number
id_col: sample number
model_params:
  alpha: 0.9
  learning_rate: 0.05
  loss: huber
  max_depth: 5
  min_samples_leaf: 10
  n_estimators: 500
  random_state: 42
  subsample: 0.7
model_type: gradient_boosting
n_folds: 5
preprocess:
- name: emsc
- deriv: 1
  name: sg
  polyorder: 2
  window_length: 7
- bin_size: 8
  name: binning
- name: standard_scaler
seed: 42
shuffle: true
split_method: group_kfold
target_col: 含水率
test_file: test.csv
train_file: train.csv
