experiment_name: tt_sqrt_xgb_d6
group_col: species number
id_col: sample number
model_params:
  colsample_bytree: 0.5
  learning_rate: 0.01
  max_depth: 6
  n_estimators: 2000
  reg_alpha: 5.0
  reg_lambda: 10.0
  subsample: 0.7
  tree_method: hist
model_type: xgb
n_folds: 5
preprocess:
- name: emsc
- deriv: 1
  name: sg
  polyorder: 2
  window_length: 7
- bin_size: 8
  name: binning
- name: standard_scaler
seed: 42
shuffle: true
split_method: group_kfold
target_col: 含水率
target_transform: sqrt
test_file: test.csv
train_file: train.csv
