experiment_name: cb_d6_emsc
group_col: species number
id_col: sample number
model_params:
  depth: 6
  iterations: 2000
  l2_leaf_reg: 10
  learning_rate: 0.01
  verbose: 0
model_type: catboost
n_folds: 5
preprocess:
- name: emsc
- deriv: 1
  name: sg
  polyorder: 2
  window_length: 7
- bin_size: 8
  name: binning
- name: standard_scaler
seed: 42
shuffle: true
split_method: group_kfold
target_col: 含水率
test_file: test.csv
train_file: train.csv
