experiment_name: log1p_xgb_deep
group_col: species number
id_col: sample number
model_params:
  colsample_bytree: 0.6
  learning_rate: 0.005
  max_depth: 5
  n_estimators: 3000
  reg_alpha: 2.0
  reg_lambda: 5.0
  subsample: 0.8
  tree_method: hist
model_type: xgb
n_folds: 5
preprocess:
- name: snv
- deriv: 1
  name: sg
  polyorder: 2
  window_length: 11
- bin_size: 8
  name: binning
- name: standard_scaler
seed: 42
shuffle: true
split_method: group_kfold
target_col: 含水率
target_transform: log1p
target_transform_lambda: 0.5
test_file: test.csv
train_file: train.csv
