experiment_name: log1p_enet_a0.1_l10.5
group_col: species number
id_col: sample number
model_params:
  alpha: 0.1
  l1_ratio: 0.5
  max_iter: 5000
model_type: elastic_net
n_folds: 5
preprocess:
- name: snv
- deriv: 1
  name: sg
  polyorder: 2
  window_length: 11
- name: standard_scaler
seed: 42
shuffle: true
split_method: group_kfold
target_col: 含水率
target_transform: log1p
target_transform_lambda: 0.5
test_file: test.csv
train_file: train.csv
