experiment_name: p4_heavyreg
group_col: species number
id_col: sample number
model_params:
  colsample_bytree: 0.3
  learning_rate: 0.01
  max_depth: 2
  min_child_samples: 30
  n_estimators: 2000
  num_leaves: 4
  reg_alpha: 50
  reg_lambda: 200
  subsample: 0.5
  verbose: -1
model_type: lgbm
n_folds: 5
preprocess:
- name: snv
- deriv: 1
  name: sg
  polyorder: 2
  window_length: 7
- bin_size: 16
  name: binning
- name: standard_scaler
seed: 42
shuffle: true
split_method: group_kfold
target_col: 含水率
test_file: test.csv
train_file: train.csv
