experiment_name: lgbm_w5_b16_verybig
group_col: species number
id_col: sample number
model_params:
  colsample_bytree: 0.5
  learning_rate: 0.005
  max_depth: 4
  min_child_samples: 15
  n_estimators: 5000
  num_leaves: 15
  reg_alpha: 5.0
  reg_lambda: 10.0
  subsample: 0.7
  verbose: -1
model_type: lgbm
n_folds: 5
preprocess:
- name: snv
- deriv: 1
  name: sg
  polyorder: 2
  window_length: 5
- bin_size: 16
  name: binning
- name: standard_scaler
seed: 42
shuffle: true
split_method: group_kfold
target_col: 含水率
test_file: test.csv
train_file: train.csv
